export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killChoose: '',
  base: '',
  acrossTwo: false,
  acrossThree: false,
  acrossFour: false,
  acrossFive: false,
  acrossSix: false,
  acrossSeven: false,
  acrossEight: false,
  acrossNine: false,
  acrossTen: false,
  allOne: false,
  allTwo: false,
  allThree: false,
  allFour: false,
  allFive: false,
  allSix: false,
  allSeven: false,
  allEight: false,
  allNine: false,
  allTen: false,
  allEleven: false,
};

export default {
  INIT_FORM_VALUE,
};
