export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killSumFifteen: false,
  killSumSixteen: false,
  killSumSeventeen: false,
  killSumEighteen: false,
  killSumNineteen: false,
  killSumTwenty: false,
  killSumTwentyOne: false,
  killSumTwentyTwo: false,
  killSumTwentyThree: false,
  killSumTwentyFour: false,
  killSumTwentyFive: false,
  killSumTwentySix: false,
  killSumTwentySeven: false,
  killSumTwentyEight: false,
  killSumTwentyNine: false,
  killSumThirty: false,
  killSumThirtyOne: false,
  killSumThirtyTwo: false,
  killSumThirtyThree: false,
  killSumThirtyFour: false,
  killSumThirtyFive: false,
  killSumThirtySix: false,
  killSumThirtySeven: false,
  killSumThirtyEight: false,
  killSumThirtyNine: false,
  killSumFourty: false,
  killSumFourtyOne: false,
  killSumFourtyTwo: false,
  killSumFourtyThree: false,
  killSumFourtyFour: false,
  killSumFourtyFive: false,
  acrossFour: false,
  acrossFive: false,
  acrossSix: false,
  acrossSeven: false,
  acrossEight: false,
  acrossNine: false,
  acrossTen: false,
  tailZero: false,
  tailOne: false,
  tailTwo: false,
  tailThree: false,
  tailFour: false,
  tailFive: false,
  tailSix: false,
  tailSeven: false,
  tailEight: false,
  tailNine: false,
  allOne: false,
  allTwo: false,
  allThree: false,
  allFour: false,
  allFive: false,
  allSix: false,
  allSeven: false,
  allEight: false,
  allNine: false,
  allTen: false,
  allEleven: false,
};

export default {
  INIT_FORM_VALUE,
};
