export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killSumFifteen: false,
  killSumSixteen: false,
  killSumSeventeen: false,
  killSumEighteen: false,
  killSumNineteen: false,
  killSumTwenty: false,
  killSumTwentyOne: false,
  killSumTwentyTwo: false,
  killSumTwentyThree: false,
  killSumTwentyFour: false,
  killSumTwentyFive: false,
  killSumTwentySix: false,
  killSumTwentySeven: false,
  killSumTwentyEight: false,
  killSumTwentyNine: false,
  killSumThirty: false,
  killSumThirtyOne: false,
  killSumThirtyTwo: false,
  killSumThirtyThree: false,
  killSumThirtyFour: false,
  killSumThirtyFive: false,
  killSumThirtySix: false,
  killSumThirtySeven: false,
  killSumThirtyEight: false,
  killSumThirtyNine: false,
  killSumFourty: false,
  killSumFourtyOne: false,
  killSumFourtyTwo: false,
  killSumFourtyThree: false,
  killSumFourtyFour: false,
  killSumFourtyFive: false,
};

export default {
  INIT_FORM_VALUE,
};
